apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: "2022-04-08T21:04:58Z"
  generation: 1
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: {{ .Values.project.namespace }}
  resourceVersion: "638761"
  uid: 98d3aafd-afee-4a2a-9f37-b23834461196
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: prisma
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          name: mysql
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: pvc-mysql2
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2022-04-08T21:04:58Z"
      lastUpdateTime: "2022-04-25T22:36:04Z"
      message: ReplicaSet "mysql-56757df4d6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-05-03T01:05:13Z"
      lastUpdateTime: "2022-05-03T01:05:13Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
