apiVersion: v1
data:
  ENDPOINT: http://myeccom2.com/graphql
  PRODENDPOINT: http://myeccom2.com/graphql
kind: ConfigMap
metadata:
  name: env-frontend
  namespace: {{ .Values.project.namespace }}
  
