apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
  creationTimestamp: "2022-04-12T03:08:21Z"
  generation: 12
  labels:
    app: backend
  name: backend
  namespace: {{ .Values.project.namespace }}
  resourceVersion: "638773"
  uid: dee53140-ceca-4369-9b77-50df9396bea4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      initContainers:
        - command:
            - /bin/sh
            - -c
            - npm run deploy
          envFrom:
            - configMapRef:
                name: env-backend
          image: stephmen/docker-ecom-backendk8:tag9
          imagePullPolicy: IfNotPresent
          name: docker-ecom-backend-init
          ports:
            - containerPort: 4444
              protocol: TCP
          resources: {}
      containers:
        - command:
            - /bin/sh
            - -c
            - npm run dev
          envFrom:
            - configMapRef:
                name: env-backend
          image: stephmen/docker-ecom-backendk8:tag9
          imagePullPolicy: IfNotPresent
          name: docker-ecom-backend
          ports:
            - containerPort: 4444
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2022-04-26T23:35:24Z"
      lastUpdateTime: "2022-04-27T15:24:40Z"
      message: ReplicaSet "backend-cf79dc879" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-05-03T01:05:14Z"
      lastUpdateTime: "2022-05-03T01:05:14Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 12
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
