apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myeccom-ingress
  namespace: {{ .Values.project.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: myeccom2.com
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 7777
        path: /
        pathType: Prefix
  - host: myeccom2.com
    http:
      paths:
      - backend:
          service:
            name: backend
            port:
              number: 4444
        path: /graphql
        pathType: Prefix
  - host: myeccom2.com
    http:
      paths:
      - backend:
          service:
            name: prisma
            port:
              number: 4466
        path: /prisma
        pathType: Prefix
