apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: {{ .Values.project.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 7777
      protocol: TCP
      targetPort: 7777
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP

