apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  labels:
    io.kompose.service: prisma
  name: prisma
  namespace: {{ .Values.project.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: "4466"
      port: 4466
      protocol: TCP
      targetPort: 4466
  selector:
    io.kompose.service: prisma
  sessionAffinity: None
  type: ClusterIP

