apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: {{ .Values.project.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 4444
      protocol: TCP
      targetPort: 4444
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP

