apiVersion: v1
data:
    PRISMA_ENDPOINT:  prisma.myeccom.com"
    #PRISMA_ENDPOINT:   http://0.0.0.0:4466"
    #PRISMA_ENDPOINT:   http://localhost:4466"
    PRISMA_SECRET:  prisma"
    APP_SECRET:  prisma"
    STRIPE_SECRET:  sk_test_bh0QAXn1x8LhONmDvaHLDKAu00sCpS9yxT"
    PORT: 4444
    #FRONTEND_URL:  http://myeccom.com:7777"
    #FRONTEND_IP:  http://myeccom.com:7777"
    #BACKEND_URL:  http://myeccom.com:4444"
    #BACKEND_IP:  http://myeccom.com:4444"
    FRONTEND_URL:  http://frontend.myeccom.com"
    FRONTEND_IP:  http://frontend.myeccom.com"
    BACKEND_URL:  http://backend.myeccom.com"
    BACKEND_IP:  http://backend.myeccom.com"

    MAIL_HOST:  smtp.mailtrap.io"
    MAIL_PORT:  2525"
    MAIL_USER:  2af1c2bddf929f"
    MAIL_PASS:  74d73a20a356dc"
    WHITELIST: http://127.0.0.1:4466, http://localhost:4466, http://myeccom.com:4466, http://0.0.0.0:4466/, http://localhost:7777, http://127.0.0.1:7777, http://myeccom.com:7777, http://localhost:4444, http://127.0.0.1:4444, http://myeccom.com:4444, http://prisma.myeccom.com, http://backend.myeccom.com, http://frontend.myeccom.com


    # FRONTEND_URL:  http://172.30.57.204:7777"
    # BACKEND_URL:  http://apollo-backend-myeccomv003.apps-crc.testing"
    # PRISMA_ENDPOINT:  http://localhost:4466"
kind: ConfigMap
metadata:
  name: backend-env-test
  namespace: default
