apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        hosts {
           192.168.64.1 host.minikube.internal
           fallthrough
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
    test:53 {
            errors
            cache 30
            forward . 192.168.64.4
    }
    myeccom.com:53 {
            errors
            cache 30
            forward . 192.168.64.4
    }
    
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-08T19:17:45Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "344"
  uid: 8c75d63f-a74e-4ff7-b5ea-5028ff5ca0d5
